### ISSUE TITLE
CSS updating doesn't work

### ISSUE THREAD

**Issue by keithpickering** [ionutvmi/SublimeMybbTplEditor#12]
Hi, great plugin. Templates are working fine, but I can't seem to get CSS working. Here's what shows up in the console:

  Traceback (most recent call last):
      File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 256, in on_post_save
        callback.on_post_save(v)
      File "mybb-tpl in C:\Users\keith\AppData\Roaming\Sublime Text 3\Installed Packages\Mybb Template Editor.sublime-package", line 216, in on_post_save
      File "mybb-tpl in C:\Users\keith\AppData\Roaming\Sublime Text 3\Installed Packages\Mybb Template Editor.sublime-package", line 245, in updateCss
      File "./urllib/request.py", line 156, in urlopen
      File "./urllib/request.py", line 475, in open
      File "./urllib/request.py", line 587, in http_response
      File "./urllib/request.py", line 513, in error
      File "./urllib/request.py", line 447, in _call_chain
      File "./urllib/request.py", line 595, in http_error_default
    urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

Any suggestions? The path to `updatecss.php` in `mybb-tpl.sublime-settings` is correct. The CSS files can be accessed just fine, but when I try to save them, I get that 503 error.

**Comment by ionutvmi** [comment]
It's been a long time but from what I can see there were some issues with making the GET request to updatecss.php.

For anyone else having this issue make sure that `css_update_url` can be accessed without any issues.
